name: Build OpenWRT For Xiaomi Router 3G

on:
  watch:
    types: started

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  CONFIG_FILE: r3g.config
  DIY_SH: diy.sh
  UPLOAD_FIRMWARE: true
  UPLOAD_COWTRANSFER: true
  SSH_ACTION: true
  TNAME: MI_R3G

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq upgrade
        sudo -E apt-get -qq install build-essential \
        asciidoc binutils bzip2 gawk gettext git libncurses5-dev libz-dev \
        patch python3 unzip zlib1g-dev lib32gcc1 libc6-dev-i386 subversion \
        flex uglifyjs gcc-multilib g++-multilib p7zip p7zip-full msmtp libssl-dev \
        texinfo libglib2.0-dev xmlto qemu-utils upx libelf-dev autoconf automake \
        libtool autopoint device-tree-compiler antlr3 gperf swig
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo timedatectl set-timezone "Asia/Shanghai"

    - name: Clone source code
      run: |
        git clone --depth 1 $REPO_URL -b $REPO_BRANCH openwrt
        #git clone --depth 1 https://github.com/siropboy/sirpdboy-package openwrt/package/sirpdboy-package
        #git clone --depth 1 https://github.com/kenzok8/openwrt-packages openwrt/package/openwrt-packages
        #git clone --depth 1 https://github.com/liuran001/openwrt-packages openwrt/package/openwrt-packages
        cd openwrt/package/lean/
        git clone --depth 1 https://github.com/rufengsuixing/luci-app-adguardhome
        git clone --depth 1 https://github.com/vernesong/OpenClash
        git clone --depth 1 https://github.com/jerrykuku/lua-maxminddb
        git clone --depth 1 https://github.com/jerrykuku/luci-app-vssr

    - name: Update and install feeds
      run: |
        cp -f feeds.conf.default openwrt/
        cd openwrt
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load custom configuration
      run: |
        cp -f $CONFIG_FILE openwrt/.config
        cp -f $DIY_SH openwrt/diy.sh
        cd openwrt
        chmod +x diy.sh
        sh diy.sh

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      if: env.SSH_ACTION == 'true'
      with:
        limit-access-to-actor: true

    - name: Organize config file
      run: |
        mkdir config
        cp openwrt/.config config/
        
    - name: Upload .config file
      uses: actions/upload-artifact@master
      with:
        name: config
        path: openwrt/config/

    - name: Download package
      run: |
        cd openwrt
        make defconfig
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    - name: Compile the firmware
      id: compile
      run: |
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 V=s
        echo "::set-output name=status::success"

    - name: Organize files
      id: organize
      if: steps.compile.outputs.status == 'success' && env.UPLOAD_FIRMWARE == 'true' && !cancelled()
      run: |
        cd openwrt/bin/targets/*/*
        rm -rf packages
        rm -f version.buildinfo feeds.buildinfo sha256sums \
        *-squashfs-rootfs0.bin *-squashfs-kernel1.bin \
        *.manifest
        md5sum config.buildinfo >> md5.txt
        md5sum *-initramfs-kernel.bin >> md5.txt
        md5sum *-squashfs-sysupgrade.bin >> md5.txt
        echo "FIRMWARE=$PWD" >> $GITHUB_ENV
        echo "::set-output name=status::success"

    - name: Upload firmware directory
      uses: actions/upload-artifact@master
      if: steps.organize.outputs.status == 'success' && !cancelled()
      with:
        name: OpenWrt_MI-R3G
        path: ${{ env.FIRMWARE }}

    - name: Upload firmware to cowtransfer
      if: steps.organize.outputs.status == 'success' && env.UPLOAD_COWTRANSFER == 'true' && !cancelled()
      run: |
        cd ${FIRMWARE}
        zip -r OpenWrt_$TNAME.zip *
        wget https://github.com/Mikubill/cowtransfer-uploader/releases/download/v0.4.23/cowtransfer-uploader_0.4.23_linux_amd64.tar.gz
        tar -zxf cowtransfer-uploader_0.4.23_linux_amd64.tar.gz
        ./cowtransfer-uploader -s -p 8 OpenWrt_$TNAME.zip
